import { useEffect, useRef, useState } from "react";
import { Engine } from "@babylonjs/core/Engines/engine";
import { createGameScene, type GameHandle } from "@/game/scene";

type Hud = { playerHp: number; enemyHp: number; timer: number; combo: number; playerMeter: number; enemyMeter: number; playerName: string; enemyName: string };
const initialHud: Hud = { playerHp: 100, enemyHp: 100, timer: Infinity, combo: 0, playerMeter: 0, enemyMeter: 0, playerName: "DC", enemyName: "WIZZ" };
const controls = [["1", "PUÑO L"], ["2", "PUÑO F"], ["3", "PATADA L"], ["4", "PATADA F"], ["5", "SALTO"], ["6", "ESQUIVA"]] as const;
function press(key: string) { window.dispatchEvent(new KeyboardEvent("keydown", { key, bubbles: true })); window.setTimeout(() => window.dispatchEvent(new KeyboardEvent("keyup", { key, bubbles: true })), 110); }

export default function GameCanvas() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const startedRef = useRef(false); const [hud, setHud] = useState(initialHud);
  useEffect(() => { const onHud = (event: Event) => setHud((event as CustomEvent<Hud>).detail); window.addEventListener("battle-hud", onHud); return () => window.removeEventListener("battle-hud", onHud); }, []);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || startedRef.current) return; startedRef.current = true; const engine = new Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true, adaptToDeviceRatio: true, alpha: true }); let handle: GameHandle | null = null; createGameScene(engine, canvas).then((next) => { handle = next; engine.runRenderLoop(() => next.scene.render()); }); const onResize = () => engine.resize(); window.addEventListener("resize", onResize); return () => { window.removeEventListener("resize", onResize); handle?.dispose(); engine.dispose(); startedRef.current = false; }; }, []);
  return <main className="arcade-frame"><canvas ref={canvasRef} className="fixed inset-0 h-full w-full outline-none" style={{ touchAction: "none" }} /><section className="arcade-ui" aria-label="Demo jugable DC Laboratorio"><a className="lab-card" href="/?demo" aria-label="Abrir el demo DCM2000"><div className="lab-eyebrow">DC LABORATORIO · DEMO</div><div className="lab-logo">DC<span>M2000</span></div><div className="lab-coming">PRÓXIMAMENTE</div><div className="lab-caption">Prototipo arcade en desarrollo</div><div className="lab-features"><span>DC vs WIZZ</span><span>6 BOTONES · VIDA ∞</span><span>3 BOTONES = ESPECIALES</span><span>SPRITES HD · TRANSPARENTES</span></div><p>Interfaz arcade de equipos y combate de demostración.</p><p>Este demo no es la versión original. Es un prototipo en desarrollo y promete ser un éxito.</p><strong className="lab-cta">TOCA PARA ENTRAR AL DEMO</strong></a><header className="arcade-topbar"><div className="team-block"><div className="portrait portrait-dc">D</div><div className="team-copy"><strong>{hud.playerName}</strong><span>DC · JUGADOR</span></div></div><div className="health-stack"><div className="health-row"><span className="health-label">VIDA ∞</span><div className="health-track"><div className="health-fill player-fill" style={{ width: "100%" }} /></div></div><div className="meter-row"><span>ENERGÍA</span><div className="meter-track"><div className="meter-fill player-meter" style={{ width: `${hud.playerMeter}%` }} /></div></div></div><div className="round-timer">∞</div><div className="health-stack right-stack"><div className="health-row"><div className="health-track"><div className="health-fill enemy-fill" style={{ width: "100%" }} /></div><span className="health-label">∞ VIDA</span></div><div className="meter-row"><div className="meter-track"><div className="meter-fill enemy-meter" style={{ width: `${hud.enemyMeter}%` }} /></div><span>ENERGÍA</span></div></div><div className="team-block right-team"><div className="team-copy right-copy"><strong>{hud.enemyName}</strong><span>WIZZ · CPU</span></div><div className="portrait portrait-wizz">W</div></div></header><footer className="six-button-bar">{controls.map(([key, label], index) => <button key={key} className={`action-button action-${index + 1}`} onPointerDown={() => press(key)}><b>{key}</b><small>{label}</small></button>)}</footer></section></main>;
}
