import { useEffect, useRef, useState } from "react";
import { Engine } from "@babylonjs/core/Engines/engine";
import { createGameScene, type GameHandle } from "@/game/scene";

type FighterName = "DC" | "Wizz";
type Hud = { playerHp: number; enemyHp: number; timer: number; combo: number; playerMeter: number; enemyMeter: number; playerName: string; enemyName: string };
const initialHud: Hud = { playerHp: 100, enemyHp: 100, timer: Infinity, combo: 0, playerMeter: 0, enemyMeter: 0, playerName: "DC", enemyName: "WIZZ" };
const controls = [["1", "PUÑO L"], ["2", "PUÑO F"], ["3", "PATADA L"], ["4", "PATADA F"], ["5", "SALTO"], ["6", "ESQUIVA"]] as const;
const roster: { name: FighterName; subtitle: string; color: string; portrait: string; image: string }[] = [
  { name: "DC", subtitle: "EL JUGADOR", color: "blue", portrait: "D", image: "/manus-storage/dchd-08_c5c1b98b.png" },
  { name: "Wizz", subtitle: "EL CICLISTA", color: "red", portrait: "W", image: "/manus-storage/wizzhd-09_fe1d7bb9.png" },
];
function press(key: string) { window.dispatchEvent(new KeyboardEvent("keydown", { key, bubbles: true })); window.setTimeout(() => window.dispatchEvent(new KeyboardEvent("keyup", { key, bubbles: true })), 110); }

function CharacterSelect({ onStart }: { onStart: (player: FighterName, enemy: FighterName) => void }) {
  const [player, setPlayer] = useState<FighterName>("DC");
  const [enemy, setEnemy] = useState<FighterName>("Wizz");
  const [activeSide, setActiveSide] = useState<"player" | "enemy">("player");
  const choose = (name: FighterName) => { if (activeSide === "player") { setPlayer(name); if (name === enemy) setEnemy(name === "DC" ? "Wizz" : "DC"); } else { setEnemy(name); if (name === player) setPlayer(name === "DC" ? "Wizz" : "DC"); } };
  return <main className="select-screen"><div className="select-scanlines" /><header className="select-header"><span className="select-kicker">DC LABORATORIO PRESENTA</span><h1>DCM<span>2000</span></h1><div className="select-subtitle">SELECCIONA TU LUCHADOR</div></header><div className="versus-select"><div className={`selection-slot ${activeSide === "player" ? "active" : ""}`} onClick={() => setActiveSide("player")}><span>JUGADOR 1</span><strong>{player}</strong></div><div className="versus-mark">VS</div><div className={`selection-slot rival ${activeSide === "enemy" ? "active" : ""}`} onClick={() => setActiveSide("enemy")}><span>RIVAL CPU</span><strong>{enemy.toUpperCase()}</strong></div></div><section className="roster-grid" aria-label="Selección de personajes">{roster.map((fighter) => <button key={fighter.name} className={`roster-card ${fighter.color} ${player === fighter.name ? "player-picked" : ""} ${enemy === fighter.name ? "enemy-picked" : ""}`} onClick={() => choose(fighter.name)}><div className="roster-portrait"><img src={fighter.image} alt={`${fighter.name} sprite`} /> </div><div className="roster-name">{fighter.name}</div><small>{fighter.subtitle}</small><div className="pick-badges">{player === fighter.name && <b>P1</b>}{enemy === fighter.name && <b>CPU</b>}</div></button>)}</section><div className="select-instructions"><span>HAZ CLIC EN UNA TARJETA PARA ELEGIR</span><span>•</span><span>DC Y WIZZ SON LOS LUCHADORES DISPONIBLES DEL PROTOTIPO</span></div><button className="start-battle" onClick={() => onStart(player, enemy)}>INICIAR BATALLA <b>▶</b></button><p className="select-disclaimer">Prototipo en desarrollo · no es la versión original</p></main>;
}

function FightCanvas({ playerName, enemyName, onBack }: { playerName: FighterName; enemyName: FighterName; onBack: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const startedRef = useRef(false); const [hud, setHud] = useState(initialHud);
  useEffect(() => { const onHud = (event: Event) => setHud((event as CustomEvent<Hud>).detail); window.addEventListener("battle-hud", onHud); return () => window.removeEventListener("battle-hud", onHud); }, []);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || startedRef.current) return; startedRef.current = true; const engine = new Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true, adaptToDeviceRatio: true, alpha: true }); let handle: GameHandle | null = null; createGameScene(engine, canvas, { playerName, enemyName }).then((next) => { handle = next; engine.runRenderLoop(() => next.scene.render()); }); const onResize = () => engine.resize(); window.addEventListener("resize", onResize); return () => { window.removeEventListener("resize", onResize); handle?.dispose(); engine.dispose(); startedRef.current = false; }; }, [playerName, enemyName]);
  return <main className="arcade-frame"><canvas ref={canvasRef} className="fixed inset-0 h-full w-full outline-none" style={{ touchAction: "none" }} /><section className="arcade-ui" aria-label="Demo jugable DC Laboratorio"><a className="lab-card" href="/?demo" aria-label="Abrir el demo DCM2000"><div className="lab-eyebrow">DC LABORATORIO · DEMO</div><div className="lab-logo">DC<span>M2000</span></div><div className="lab-coming">PRÓXIMAMENTE</div><div className="lab-caption">Prototipo arcade en desarrollo</div><div className="lab-features"><span>{playerName} VS {enemyName.toUpperCase()}</span><span>6 BOTONES · VIDA ∞</span><span>3 BOTONES = ESPECIALES</span><span>SPRITES HD · TRANSPARENTES</span></div><p>Interfaz arcade de equipos y combate de demostración.</p><p>Este demo no es la versión original. Es un prototipo en desarrollo y promete ser un éxito.</p><strong className="lab-cta">TOCA PARA ENTRAR AL DEMO</strong></a><button className="back-to-select" onClick={onBack}>SELECCIÓN</button><header className="arcade-topbar"><div className="team-block"><div className="portrait portrait-dc">{playerName === "DC" ? "D" : "W"}</div><div className="team-copy"><strong>{hud.playerName}</strong><span>{playerName} · JUGADOR</span></div></div><div className="health-stack"><div className="health-row"><span className="health-label">VIDA ∞</span><div className="health-track"><div className="health-fill player-fill" style={{ width: "100%" }} /></div></div><div className="meter-row"><span>ENERGÍA</span><div className="meter-track"><div className="meter-fill player-meter" style={{ width: `${hud.playerMeter}%` }} /></div></div></div><div className="round-timer">∞</div><div className="health-stack right-stack"><div className="health-row"><div className="health-track"><div className="health-fill enemy-fill" style={{ width: "100%" }} /></div><span className="health-label">∞ VIDA</span></div><div className="meter-row"><div className="meter-track"><div className="meter-fill enemy-meter" style={{ width: `${hud.enemyMeter}%` }} /></div><span>ENERGÍA</span></div></div><div className="team-block right-team"><div className="team-copy right-copy"><strong>{hud.enemyName}</strong><span>{enemyName.toUpperCase()} · CPU</span></div><div className="portrait portrait-wizz">{enemyName === "Wizz" ? "W" : "D"}</div></div></header><footer className="six-button-bar">{controls.map(([key, label], index) => <button key={key} className={`action-button action-${index + 1}`} onPointerDown={() => press(key)}><b>{key}</b><small>{label}</small></button>)}</footer></section></main>;
}

export default function GameCanvas() {
  const demoMode = new URLSearchParams(window.location.search).has("demo");
  const [screen, setScreen] = useState<"select" | "fight">(demoMode ? "fight" : "select");
  const [matchup, setMatchup] = useState<{ player: FighterName; enemy: FighterName }>({ player: "DC", enemy: "Wizz" });
  if (screen === "select") return <CharacterSelect onStart={(player, enemy) => { setMatchup({ player, enemy }); setScreen("fight"); }} />;
  return <FightCanvas key={`${matchup.player}-${matchup.enemy}`} playerName={matchup.player} enemyName={matchup.enemy} onBack={() => setScreen("select")} />;
}
